name: Test
on:
  pull_request:

permissions:
  contents: read

jobs:
  all-ok:
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@v7
      with:
        persist-credentials: false
    - uses: ./
      with:
        path: ./test/format
        longside: 300
        formats: "JPEG, PNG"
        always_success: true
  format-ng:
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@v7
      with:
        persist-credentials: false
    - uses: ./
      with:
        path: ./test/format
        longside: 300
        formats: "JPEG"
        always_success: true
  format-ng2:
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@v7
      with:
        persist-credentials: false
    - uses: ./
      with:
        path: ./test/format/jpeg
        longside: 300
        formats: "J, PEG"
        always_success: true
  dpi-ng:
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@v7
      with:
        persist-credentials: false
    - uses: ./
      with:
        path: ./test
        formats: "JPEG, PNG"
        longside: 300
        level: warning
        always_success: true
  longside-ng:
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@v7
      with:
        persist-credentials: false
    - uses: ./
      with:
        path: ./test/format/png
        longside: 500
        formats: "PNG"
        level: warning
        always_success: true
  pixel-ng:
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@v7
      with:
        persist-credentials: false
    - uses: ./
      with:
        path: ./test/format/jpeg
        longside: 300
        pixel_limit: 900000
        level: warning
        always_success: true
  no-check:
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@v7
      with:
        persist-credentials: false
    - uses: ./
      with:
        path: ./test/
        dpi: 0
        longside: 0
        pixel_limit: 0
        formats: ""
        level: error
        always_success: false
